name: diffusion_cuda128

channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - nodefaults

dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - pillow
  - imageio
  - tifffile
  - h5py
  - pyyaml
  - tqdm
  - tensorboard
  - pip
  - pip:
      - --index-url https://pypi.tuna.tsinghua.edu.cn/simple
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.11.0+cu128
      - torchvision==0.26.0+cu128
      - torchaudio==2.11.0+cu128
